import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";
import { getEnvelope } from "@/lib/db";
import { buildEnvelopePdf } from "@/lib/pdfBuild";

// Serves the finished document. Built here rather than in the
// recipient's browser, so a hundred-page envelope on a phone can't run
// out of memory halfway through with an unhelpful error.
//
// The PDF is a CACHE, not a record. Everything needed to rebuild it —
// page images, field values, the audit log — is stored permanently, so
// a cached file can be deleted at any time and regenerated byte-for-
// byte later. That is what makes the purge below safe.

export const PDF_TTL_MS = 30 * 24 * 60 * 60 * 1000;

function pdfDir() {
  const dbPath = process.env.DB_PATH || path.join(process.cwd(), "dollarsign.db");
  const dir = path.join(path.dirname(dbPath), "pdfs");
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

/**
 * Deletes cached PDFs untouched for 30 days. Runs opportunistically on
 * each build rather than on a schedule: there is no cron in this app,
 * and tying the sweep to the thing that creates the files means the two
 * can never drift apart.
 *
 * Keyed on last ACCESS, not creation — a document downloaded on day 29
 * survives, so a customer who fetches theirs monthly never waits for a
 * rebuild.
 */
function sweepStaleCache(dir) {
  let removed = 0;
  try {
    const cutoff = Date.now() - PDF_TTL_MS;
    for (const name of fs.readdirSync(dir)) {
      if (!name.endsWith(".pdf")) continue;
      const p = path.join(dir, name);
      try {
        if (fs.statSync(p).mtimeMs < cutoff) { fs.unlinkSync(p); removed++; }
      } catch { /* raced with another request — fine, it's a cache */ }
    }
  } catch (err) {
    console.error("pdf cache sweep failed:", err);
  }
  return removed;
}

export async function GET(req, { params }) {
  const envelope = getEnvelope(params.id);
  if (!envelope) return NextResponse.json({ error: "not found" }, { status: 404 });

  if (envelope.status !== "completed") {
    return NextResponse.json(
      { error: "This envelope isn't complete yet, so there's no final document to download." },
      { status: 409 }
    );
  }

  const dir = pdfDir();
  const file = path.join(dir, `${params.id}.pdf`);
  const filename = `${envelope.documentName ? envelope.documentName.replace(/[^\w.\- ]+/g, "").trim().slice(0, 60) || envelope.trackingId : envelope.trackingId}.pdf`;

  let bytes;
  let cached = false;
  try {
    if (fs.existsSync(file)) {
      bytes = fs.readFileSync(file);
      cached = true;
      // Touch it so the 30-day clock tracks last use, not creation.
      const now = new Date();
      try { fs.utimesSync(file, now, now); } catch { /* non-fatal */ }
    } else {
      bytes = Buffer.from(await buildEnvelopePdf(envelope));
      try { fs.writeFileSync(file, bytes); } catch (err) {
        // A full disk shouldn't cost the customer their download.
        console.error("could not cache pdf:", err);
      }
      sweepStaleCache(dir);
    }
  } catch (err) {
    console.error("pdf build failed:", err);
    return NextResponse.json(
      { error: "We couldn't build your document. Please try again, or email support@dollarsign.io." },
      { status: 500 }
    );
  }

  return new NextResponse(bytes, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(bytes.length),
      "X-Pdf-Cache": cached ? "hit" : "miss",
      // Never let a shared cache hold a signed document.
      "Cache-Control": "private, max-age=0, must-revalidate",
    },
  });
}
